services:
  - type: web
    name: booga-war-logs-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: RENDER
        value: true
    disk:
      name: bot-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
